owner: MigraineKR
repo: ihs.status

sites:
  - name: ihs-headache.org
    url: https://ihs-headache.org/
        
status-website:
  cname: ihs.status.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | IHS
  introTitle: "**Status** for International Headache Society"
  introMessage: International Headache Society WebMonitor
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://ihs-headache.org/en/
    - title: YouTube
      href: https://www.youtube.com/@internationalheadachesocie9108
    - title: Twitter
      href: https://twitter.com/ihs_official
    - title: Instagram
      href: https://www.instagram.com/ihsheadache
    - title: Facebook
      href: https://www.facebook.com/IHSheadache/
