owner: MigraineKR
repo: ihs.status

sites:
  - name: ihs-headache.org
    url: https://ihs-headache.org/
        
status-website:
  cname: ihs.status.migraine.kr
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | International Headache Society
  introTitle: "**Status** for International Headache Society"
  introMessage: International Headache Society WebMonitor
  navbar:
    - title: Status
      href: /
    - title: YouTube
      href: https://www.youtube.com/@internationalheadachesocie9108
